# Build for Shepard

name: CI

# Controls when the action will run. Will happen when a new release is published.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a job called "publish_to_pypi"
  publish_to_pypi:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # checkout the published branch
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # run python3 build
      - run: python3 -m pip install --upgrade build && python3 -m build

      # publish results of python3 build command, use PYPI_API_TOKEN to authenticate.
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  # This workflow contains a job called "publish_to_dockerhub"
  push_to_registry:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

        # checkout the published branch
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # extract metadata from dockerhub
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: sheparddeploybot/shepard-worker-container

      # build and push image to dockerhub
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./code/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}